FROM debian:9.1

RUN apt-get update  
RUN apt-get install -y ca-certificates

COPY gopath/bin/labeler /labeler
COPY scripts/labeler.sh /labeler.sh

RUN chmod a+x /labeler.sh

ENTRYPOINT ["/labeler.sh"]
