FROM debian:9.1

RUN apt-get update  
RUN apt-get install -y ca-certificates

COPY gopath/bin/recognizer /recognizer
COPY scripts/recognizer.sh /recognizer.sh

RUN chmod a+x /recognizer.sh

ENTRYPOINT ["/recognizer.sh"]
